# fly.toml file generated for muhar-tipping on 2022-09-14T02:21:03+10:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "muhar-tipping"
primary_region = "syd"

[processes]
  web = "yarn start"

[deploy]
  release_command = "yarn db:deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
  processes = ["web"]