# fly.toml file generated for muhar-tipping on 2022-09-14T02:21:03+10:00
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "muhar-tipping"
primary_region = "syd"

[env]
  NEXTAUTH_URL="https://tipping.muhar.xyz"
  GOOGLE_CLIENT_ID="734459720589-duo0ouap4tc1fnd5t0tp23lslrts9ai9.apps.googleusercontent.com"

[build]

[deploy]
  release_command = "pnpx prisma migrate deploy"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
